#! /bin/sh
# preinst script for vttest

set -e

PRI=10
ALT=vttest
PKG=vttest-base

BINDIR=/usr/bin
MANDIR=/usr/share/man/man1

if [ ! -f /usr/bin/$PKG \
    -a -f /usr/bin/$ALT \
    -a ! -f /usr/bin/vttest-cur ]
then
	mv $BINDIR/$ALT      $BINDIR/$PKG 
	mv $MANDIR/$ALT.1.gz $MANDIR/$PKG.1.gz

	update-alternatives \
		--install \
			$BINDIR/$ALT $ALT \
			$BINDIR/$PKG $PRI \
		--slave $MANDIR/$ALT.1.gz $ALT.1.gz \
			$MANDIR/$PKG.1.gz

fi

#DEBHELPER#

exit 0
